### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by ghoste0001** [vendetta-mod/Vendetta#199]
i was chatting with others. made a joke, then some time later everyone started spamming tomato reactions on all of my messages.
ended up getting perm banned for some reason along with the guy that was spamming the reactions.

the mod probably had a grudge against me for some reason and used the whole tomato thing as an excuse to ban me cause i dont see any other reason why i'd be banned.

im not gonna participate in that shitshow of a chat anymore, just gonna browse themes.

username: ghoste0001

if this ban appeal gets denied then i want a reason on why i got banned and also the reason on why it got denied. if it doesnt get denied then great.

**Comment by ghost** [comment]
uh actually 🤓 you were 🍅'd out the chat L bozo

**Comment by ghoste0001** [comment]
thats not an excuse for a perm ban

**Comment by ghost** [comment]
find a server who cares

**Comment by mollyvita** [comment]
Hello! Thank you for reaching out. Unfortunately, there's not so much we can do. We can give you an access to our plugins on https://vd-plugins.github.io/web and a free 🍅

**Comment by ghost** [comment]
but yeah @Withoutruless I unbanned you

**Comment by JustSxm** [comment]
> but yeah @Withoutruless I unbanned you

Could you check https://github.com/vendetta-mod/Vendetta/issues/195 ?
You're the one who banned me aswell and it got me confused.

Thank you 🙌

**Comment by ghost** [comment]
no you're genuinely annoying lol

**Comment by JustSxm** [comment]
> no you're genuinely annoying lol

I'm sorry if I annoyed you, but it was just a joke that even a mod joined in.

I wont do it again tho, I like the people in the server so I'll behave 🙏

**Comment by ghost** [comment]
since when is spam a joke?
that mod should've corrected you.

**Comment by mollyvita** [comment]
if you want plugins use https://vd-plugins.github.io/web

**Comment by JustSxm** [comment]
It was just a cute cat, it was more of a "community" spam, not me spamming. I didnt even think people would send it for this long. Plus, when a staff member jumped in and said to stop everyone stopped except one guy. That guy indeed deserved whatever happened to him for being a smart ass, but I was just participating with the other sillies

I felt like the community was chill so I didnt think that a bit would get me banned, I even made sure to read the rules (which barely anyone does) before even posting it because I was getting along with the people around and I liked the "vibe"

Again I appologize if I went too far, its my fault for assuming it would be okay, but I really like chatting with people over there and I'll be more careful about what I'm sending to not start something like this again

**Comment by JustSxm** [comment]
> if you want plugins use https://vd-plugins.github.io/web

I appreciate the link, but I really like the community and Im not looking for plugins/new vendetta ipas I just want my ban lifted so I can enjoy chatting and wasting my time in general again, Im there for the community

**Comment by ghost** [comment]
Hey, I believe the mod who joined in is me, sorry about that—, @JustSxm I am sorry to bring it to you but you will not be unbanned and it's best to leave this to rest. You were banned for spamming that "cute cat" you've mentioned two replies above. "Community" spam or not, you still participated in a spamming session and that is more than enough to prove your guilt. If you keep asking for an unban in GitHub issues you will be denied access to the issues altogether. This place isn't a place for ban appeals.

Move on and have a good day.. or night.

**Comment by JustSxm** [comment]
> Hey, I believe the mod who joined in is me, sorry about that—, @JustSxm I am sorry to bring it to you but you will not be unbanned and it's best to leave this to rest. You were banned for spamming that "cute cat" you've mentioned two replies above. "Community" spam or not, you still participated in a spamming session and that is more than enough to prove your guilt. If you keep asking for an unban in GitHub issues you will be denied access to the issues altogether. This place isn't a place for ban appeals.
> 
> Move on and have a good day.. or night.

Hi, no I was aiming at Cynthia here, but I guess you were there too

Anyway I appreciate the response from you and lucy, I just find it unfortunate I get banned for that when I didnt even get warned or anything when two staff members where there at the time of the incident, but banned an hour later by another one. On top of that it was my first day in the server and I was still "gauging" what was okay and what was not, and apparently I went too far.

Hopefully you reconsider,
Otherwise thanks for your guys time anyway. Its just disheartening that I'm willing to behave well and everything, but you guys just rather keep someone banned for a honest mistake and instead just encouraging to make an alt to access Vendetta's ipas & plugins

Good day or good night to both of you aswell

**Comment by ghost** [comment]
@JustSxm I unbanned you

**Comment by JustSxm** [comment]
> @JustSxm I unbanned you

Thank you 🙏
