### ISSUE TITLE
Vendetta Crashes on Startup

### ISSUE THREAD

**Issue by Obscure2020** [vendetta-mod/Vendetta#202]
I just got a notification from Vendetta Manager that a new update was ready. It downloaded and installed version 207.23 without issue. However, Vendetta will not open at all any more. It simply crashes on startup, and gave me this crash log:

```
time: 1702063535166
msg: android.system.ErrnoException: open failed: EISDIR (Is a directory)
stacktrace: java.io.FileNotFoundException: /data/user/0/dev.beefers.vendetta/cache/mmkv/https:/vd-plugins.github.io/proxy/vendetta.nexpid.xyz/plugin-browser: open failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.discord.cache.CacheModule.readLargeEntry(SourceFile:59)
	at com.discord.cache.CacheModule.access$readLargeEntry(Unknown Source:0)
	at com.discord.cache.CacheModule$1.invoke(SourceFile:6)
	at com.discord.cache.CacheModule$1.invoke(SourceFile:1)
	at lg.a$a.run(Unknown Source:2)
Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
	at libcore.io.IoBr
```

Out of curiosity, I have now checked the Vendetta Discord server to see if anyone else knows about this. Hmm, this looks awfully relevant!

![Pre_Knowledge](https://github.com/vendetta-mod/Vendetta/assets/69320464/42094e2a-7fa1-4d6a-b745-6edf26d35b50)

Here's the problem with that advice: I have my Vendetta Manager set to the Stable branch.

![Manager_Proof](https://github.com/vendetta-mod/Vendetta/assets/69320464/73a355da-3f50-4697-8e72-800906639f26)

If all versions above 207.7 were **_known_** to be broken, then _why was version 207.23 released through the Stable branch???_

**Comment by wingio** [comment]
we don't control discord updates

**Comment by Meganium97** [comment]
Can you try the alpha channel, 210.5?

**Comment by purepani** [comment]
Hello,
The error for me materializes as being unable to open the plugins page.
This is not fixed on the alpha channel

**Comment by sbot50** [comment]
After some testing I concluded this:

Let's first start off with that I personally use the latest version of discord however anything I will discuss here has been tested on 207.7 aswell.

Firstly, to fix the issue clear your cache and the entire data of your app, you will lose as your plugins and themes but you won't need to reinstall discord all together + you'll have a working vendetta again.

Secondly, this seems to only happen when installing a lot of plugins using the plugin-browser plugin, after scrolling down a while it gets very laggy, downloads take way longer, pressing gets laggy etc.

When installing plugins using the discord plugins channel it seems to work fine and won't crash vendetta. Furthermore, it seems that if you search for a plugin in the plugin-browser instead of scrolling it also works fine and doesn't lag.

What I *think* is happening (this is not based an any evidence since I don't know how to test this effectively) is that when scrolling down in the plugin-browser (btw scrolling down too far makes it loop back which is also weird) it probably doesn't install the plugin you want correcly/fully turning it into an uncomplete file which crashes the plugins tab. Again, I don't have any evidence for this so this needs to be investigated futher.

For now, I suggest staying away from the plugin-browser all together (or atleast filter by search before installing), this should prevent the issue from accuring. However, this is just what I experienced and I could have just gotten lucky or smth.

(On a sidenote, I haven't had anything break (except this) with vendetta on the latest discord version (208.17) so if anyone could clarify what exactly should be broken that isn't in 207.7 that would be great.)
