### ISSUE TITLE
Remove Phone Number Verification from the Server

### ISSUE THREAD

**Issue by FelicityIris** [vendetta-mod/Vendetta#225]
I don't want to share my phone number with Discord for accessing the server. It is quite irritating to try to reach mods in their DMs to get verified.

**Comment by mollyvita** [comment]
maybe you should suggest it in #support

**Comment by FelicityIris** [comment]
> maybe you should suggest it in #support 

i wasn't verified when i wrote the issue.

**Comment by mollyvita** [comment]
skill issue. just verify your number fr it wont make you explode

**Comment by FelicityIris** [comment]
> skill issue. just verify your number fr it wont make you explode

I'm not interested in sharing my phone number _to discord_ for privacy reasons.

**Comment by mollyvita** [comment]
sounds like pixel 4a grapheneos

**Comment by Cynosphere** [comment]
> I'm not interested in sharing my phone number to discord for privacy reasons.

womp womp, just don't get your account stolen its not that hard

**Comment by FelicityIris** [comment]
> > I'm not interested in sharing my phone number to discord for privacy reasons.
> 
> womp womp, just don't get your account stolen its not that hard

who said anything about account getting stolen?

**Comment by mollyvita** [comment]
imo this issue should be closed, its literally pointless, verifying a phone number wont send it to cia

**Comment by FelicityIris** [comment]
> imo this issue should be closed, its literally pointless, verifying a phone number wont send it to cia

"I don't want to share my phone number."

That's not hard to understand.

**Comment by mollyvita** [comment]
"i don't like X that's why you should remove X from a 30k+ community"

that's not hard to understand 😕

**Comment by Cynosphere** [comment]
you are paranoid for what reason? what are they going to do with it? literally nothing except remove it from your account if another account tries to use it

**Comment by FelicityIris** [comment]
> "i don't like X that's why you should remove X from a 30k+ community"
> 
> that's not hard to understand 😕

Bad Analogy

**Comment by mollyvita** [comment]
ok pixel 4a grapheneos

**Comment by FelicityIris** [comment]
> you are paranoid for what reason? what are they going to do with it? literally nothing except remove it from your account if another account tries to use it

i dont want to share my phone number, period. it is personal info and i dont want to share it. email verification is enough for the server.

**Comment by mollyvita** [comment]
how could you know if it's enough while you're literally unverified (+ you don't know how to moderate 30k+ server)

**Comment by Cynosphere** [comment]
womp womp, not disabling it because we already have a spambot problem (which is most likely from compromised accounts) and disabling phone verification would make it worse

literally no one is going to see your phone number without getting access to your account, nor is discord going to even check what personal info is on said number to link it to you like its some CCP social credit, privacy schizo.

**Comment by FelicityIris** [comment]
ja okej, i am closing this. im not interested in furthering this waste of time. its clear you dont care about choice or privacy.

**Comment by PalmDevs** [comment]
> I'm not interested in sharing my phone number _to discord_ for privacy reasons.

> i dont want to share my phone number, period.

That's great for you, but a server with 30K members and less than 30 moderators requires a legitimate account and not just some burner account anyone can make.

**Comment by mollyvita** [comment]
> its clear you dont care about choice or privacy.

its clear you dont understand how moderation works ☠️

**Comment by Cynosphere** [comment]
I do care about freedom of choice and privacy. But I'm also a realist and you clearly aren't. I would be in the same boat as you if I didn't link my phone to my account back in 2018/2019, let alone if I didn't have friends that had numbers for my alts as well, because they've gotten phone locked before.

You're instead wasting your time arguing over the most pointless thing instead of just accepting the facts and either coping and linking your number, finding a work around or just moving on.

You're trusting a service that people heavily debate about on if your data is even being sold or not as is, yet you're going to fight volunteer contributors that take their time to develop and/or moderate a chatroom over one minute point and not even care about the bigger picture? Pathetic.

Just delete your account if you care that much about your privacy. But you won't, because you can't, because you let your friends bully you into disregarding your freedom of choice. **You have no room to try and pull the "muh freedom/privacy" card when you're not being proactive with it to begin with.**

Plus you're arguing **on a Microsoft owned platform** that REALLY doesn't value your privacy. How's that for devils advocate?

**Comment by FelicityIris** [comment]
> I do care about freedom of choice and privacy.

You don't and I will explain why in detail below.

> You're instead wasting your time arguing over the most pointless thing [...]

I already realized that and closed the thread if you bothered to read my last msg.

> You're trusting a service that people heavily debate about on if your data is even being sold or not as is [...]

That's not my responsibilty. The devs have chosen to make Discord their only platform to directly communicate and install Themes & Plugins.

> Just delete your account if you care that much about your privacy. But you won't, because you can't, because you let your friends bully you into disregarding your freedom of choice. **You have no room to try and pull the "muh freedom/privacy" card when you're not being proactive with it to begin with.**

This is just petty ignorance and presumptious behaviour. I had been away from discord, on matrix, for an year. Unfortunately devs these days think Discord is the Forums alternative and make it their primary, and in this case, only form of communication and installing Plugins & Themes. That is why I had to recreate an account. You are one of them responsible.

> Plus you're arguing **on a Microsoft owned platform** that REALLY doesn't value your privacy. How's that for devils advocate?

Again, you have chosen to host your repository on GitHub. So stop victim blaming me. 

And stop continuing this thread when I have closed it and clearly said that I don't want to continue it.

**Comment by sepruko** [comment]
womp womp

**Comment by janisslsm** [comment]
> That's not my responsibilty. The devs have chosen to make Discord their only platform to directly communicate and install Themes & Plugins.

https://vd-plugins.github.io/web

**Comment by ayunami2000** [comment]
I was here

Also btw just use some site like https://receive-sms-free.cc/

Ez phone verification then u can use it

Ur not gonna get special treatment bc of the precedent that sets for other users and potential malicious actors who want or try to bot the server.
